buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
}

apply plugin: 'net.minecraftforge.gradle'

def modVersion = '1.2'
version = "$modVersion-1.12.2"
group = 'com.telepathicgrunt.wits'
archivesBaseName = 'wits-forge'

sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'
    runs {
        client { workingDirectory project.file('run') }
        server { workingDirectory project.file('run') }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2864'
}

processResources {
    inputs.property 'version', modVersion
    filesMatching(['mcmod.info', 'version.properties']) { expand version: modVersion }
}

jar.finalizedBy('reobfJar')

sourceSets.each {
    def dir = layout.buildDirectory.file("sourcesSets/$it.name").get().asFile
    it.output.resourcesDir = dir
    it.java.outputDir = dir
}
